### ISSUE TITLE
Small widget doesn't handle the display of 3-digit fee rates well

### ISSUE THREAD

**Issue by so7ow** [yanascz/bitcoin-widgets-ios#4]
See screenshot. Hard to read, not tidy. 

![image](https://github.com/yanascz/bitcoin-widgets-ios/assets/633079/0b891071-94ee-4d9b-8286-5176f7258533)

**Comment by yanascz** [comment]
Thanks, I'm aware of this behaviour. I'm not sure there's an elegant solution for this but I'll take a look when I have a moment.

**Comment by so7ow** [comment]
Edited for snark. Good luck, I hope you find a solution.

**Comment by yanascz** [comment]
Well, it's the mighty iOS that ended up rendering what's captured in the attached screenshot. I'm just not sure that the SwiftUI layout engine is as powerful as e.g. CSS Flexbox that would allow for a pretty simple fix, while preserving the functionality I'd like to preserve. Feel free to create a pull request if you know how to elegantly fix it, I'll be happy to learn from you.

**Comment by yanascz** [comment]
I discussed with an iOS developer and there are some options how to handle this. Now I just need to find some time to fix it, test it and release it.

**Comment by yanascz** [comment]
Finally started working on the fix. Which one do you find better?
<img width="185" alt="image" src="https://github.com/yanascz/bitcoin-widgets-ios/assets/37251117/bef8281d-a415-4bb9-9c29-4dc32cd7008e">
<img width="185" alt="image" src="https://github.com/yanascz/bitcoin-widgets-ios/assets/37251117/983a9989-6127-4945-ad7c-ff83b45ae3df">

**Comment by so7ow** [comment]
Those both seem fine to me. I guess I might prefer the larger one, just for my poor aging eyes. Thanks for looking into it.

**Comment by yanascz** [comment]
I prefer the first one as well. I'll be testing the fix for a while since I had to adapt the app to iOS 17. Hopefully it'll be out soon!

**Comment by yanascz** [comment]
Fixed in [version 1.5.2](https://github.com/yanascz/bitcoin-widgets-ios/releases/tag/v1.5.2).
