### ISSUE TITLE
Feature Request: Halving ETA

### ISSUE THREAD

**Issue by bitwalt** [yanascz/bitcoin-widgets-ios#5]
Hi! I'm a user of your widget, really cool man! 
I saw this recently https://halving.live/ and I thought it would be cool to have a counter to the next halving as a widget. 
Inspecting the source there is JS code for calculation from mempool.space data. I wish I could help you but I don't know Swift, anyway thanks

**Comment by yanascz** [comment]
Hey Walter, thanks for this idea! I'll think about it and investigate the possibilities for a countdown widget when I have a moment. If I'm able to come up with a meaningful solution, I'll post some screenshots.

**Comment by yanascz** [comment]
WIP for different regions. Ideas?
<img width="149" alt="image" src="https://github.com/yanascz/bitcoin-widgets-ios/assets/37251117/6f1afe97-8cb6-4926-a7c6-b313a69989b5">
<img width="149" alt="image" src="https://github.com/yanascz/bitcoin-widgets-ios/assets/37251117/7e9a4046-d675-42f3-9e92-03a15dbb3844">

**Comment by bitwalt** [comment]
Nice! I like them both, really clean design

**Comment by yanascz** [comment]
After feedback from my colleagues, I decided to unify the layout with existing widgets. This is probably the final version:
<img width="176" alt="image" src="https://github.com/yanascz/bitcoin-widgets-ios/assets/37251117/1c3db161-091a-4297-8759-ab09a61a1ede">
<img width="176" alt="image" src="https://github.com/yanascz/bitcoin-widgets-ios/assets/37251117/a272e191-621d-4619-a76f-3f62ddc5d34f">

Not sure about the colour, though. Which one do you find better? I didn't want to use orange (reserved for block height in the Node Status widget) or purple (reserved for block height in the Mempool Status widget). Green seems inappropriate as it implies growth while red implies decrease.

**Comment by yanascz** [comment]
Fixed in [version 1.6](https://github.com/yanascz/bitcoin-widgets-ios/releases/tag/v1.6).

**Comment by bitwalt** [comment]
Hey great! well done, yellow in my opinion is perfect as a color! Tipped you some sats :)
