### ISSUE TITLE
Widget not availbale on lockscreen

### ISSUE THREAD

**Issue by you-are-el** [yanascz/bitcoin-widgets-ios#6]
The widget is unfortunately not available on the lockscreen. This would be a great addition.

**Comment by yanascz** [comment]
What widget exactly? See the attached screenshot.
![Screenshot 2024-01-15 at 13 28 17 jpeg](https://github.com/yanascz/bitcoin-widgets-ios/assets/37251117/03fb0f4c-4d4e-4b9a-8d0c-bddf24080b84)
