### ISSUE TITLE
Sats per dollar wrong display

### ISSUE THREAD

**Issue by Estrama9** [yanascz/bitcoin-widgets-ios#7]
Sats per dollar display a ":" between the second digit and the third digit like and time display instead of the four digit of price as you can see in the photo below 

![image](https://github.com/yanascz/bitcoin-widgets-ios/assets/124655087/d35ee723-c4bf-4acb-ac5c-c390656c1367)

**Comment by yanascz** [comment]
Hey @Estrama9, iťs not a bug, it’s a feature. 🙂 There’s a reason why it’s called Moscow Time, see https://x.com/moscowtimebot for example.

And it’s possible to configure it in widget settings:
![image](https://github.com/yanascz/bitcoin-widgets-ios/assets/37251117/7f0c6c9b-3688-4cdf-9788-c1799694e5ea)

**Comment by Estrama9** [comment]
Sorry my bad. I figured out my mistake after writing it.
I followed your suggestion and I changed the Moscow time to sats per dollar 
Thanks for answer and correcting me.
Great widgets. Keep the good work
Cheers
